// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("ExtraLINQ")]
[assembly: AssemblyTitleAttribute("ExtraLINQ")]
[assembly: GuidAttribute("8269e986-f931-4695-a8aa-eaf0f437b2c4")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright Marius Schulz 2014")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.0";
    }
}
