// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("ExtraLINQ.Tests")]
[assembly: AssemblyTitleAttribute("ExtraLINQ Unit Tests")]
[assembly: GuidAttribute("032b2aa9-3158-4fc7-907e-1ded01fc9dd8")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright Marius Schulz 2015")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.0";
    }
}
